### PR TITLE
bringing the style from airbnb

### PR DESCRIPTION
**Pull request by ggrocco**

### CODE REVIEW

**Review by augustogoldoni-jaya — APPROVED** [review]

**Review by eliasousa — APPROVED** [review]
🚀

**Review by patricia-tonella — APPROVED** [review]
👏

**Review by dbalexandre — APPROVED** [review]

**Review by davithss — APPROVED** [review]
🔝

**Review by lcalmeida — APPROVED** [review]
Let's do it! We can use this initial version and adjust as long we learn what fits best for us

**Review by aamachado — APPROVED** [review]

**Pull request merged**
